<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>SakhandDm</AssemblyName>
    <RootNamespace>SakhandDm</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.3.0</Version>
    <Product>Download Manager</Product>
    <Authors>Sakhand Morami</Authors>
    <Company>Sakhand</Company>
    <Description>دانلود منیجر سریع و فارسی برای ویندوز — ۳۲ ترد، یوتیوب/اینستاگرام/پینترست</Description>
    <InvariantGlobalization>false</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="app.ico" />
  </ItemGroup>

</Project>
